In [9]:
import numpy as np
a=np.array([4,5,6,7,8,8])
b=np.array([3,435,26,17,38,48])
np.add(a,b)


array([  7, 440,  32,  24,  46,  56])

In [59]:
text='NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.'
l=text.split(" ")
arr=np.array(text.split(" "))



library
Python
programming
language,
adding
support
large,
multi-dimensional
arrays
matrices,
collection
high-level
mathematical
functions
operate
arrays.


In [22]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2,3])
arr3=arr1*arr2
arr3


array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [25]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2])
arr3=arr1*arr2
arr3
#ab broadcasting nhe ho pae ge shapes match nhe krte par aga rsingle element hiota to ho jata


ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [24]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([1])
arr3=arr1*arr2
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#functional behaviour analysis krna he har function ka input ot output dekhna he wo kese behvae kr rraha he


In [47]:
arr='how dare you! you can\'t do that! Mr Ashhad focus. Do you want a brak? or if you don\'t want, we can practice'
l=arr.split('.')
l


["how dare you! you can't do that! Mr Ashhad focus",
 " Do you want a brak? or if you don't want, we can practice"]

In [50]:
#filter karne ke liye , true false me convert krne k liye
l=np.array([-0.212,.12,.12,-.1211])
l>0

array([False,  True,  True, False])

In [75]:
# agar hame array ke har elemnt par ko ifunction apply krna he to np.vectorize kre ge

text='NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.'
l=text.split(" ")
arr=np.array(text.split(" "))

print(arr)
lnth=np.vectorize(len)
print(arr[lnth(arr)>5])
print(arr[(np.vectorize(len))(arr)>5])

for i in arr:
    if len(i)>5:
        print(i)


['NumPy' 'is' 'a' 'library' 'for' 'the' 'Python' 'programming' 'language,'
 'adding' 'support' 'for' 'large,' 'multi-dimensional' 'arrays' 'and'
 'matrices,' 'along' 'with' 'a' 'large' 'collection' 'of' 'high-level'
 'mathematical' 'functions' 'to' 'operate' 'on' 'these' 'arrays.']
['library' 'Python' 'programming' 'language,' 'adding' 'support' 'large,'
 'multi-dimensional' 'arrays' 'matrices,' 'collection' 'high-level'
 'mathematical' 'functions' 'operate' 'arrays.']
['library' 'Python' 'programming' 'language,' 'adding' 'support' 'large,'
 'multi-dimensional' 'arrays' 'matrices,' 'collection' 'high-level'
 'mathematical' 'functions' 'operate' 'arrays.']
library
Python
programming
language,
adding
support
large,
multi-dimensional
arrays
matrices,
collection
high-level
mathematical
functions
operate
arrays.


In [68]:
variabl me function store ho sakta he
prn=print
prn('asd')

asd


In [148]:
#fancy indexing
arr5=np.array([-1,-1,45,6,8,9,1,11])
arr5[[2,3]]
s=[2,6,]
print(arr5[s])

[45  1]


In [128]:
salary=np.array([0,1,-1,1000,5000])
np.where(salary<=0,25000,salary)

array([25000,     1, 25000,  1000,  5000])

In [129]:
salary.sum()
salary.mean()
salary.cumsum()

array([   0,    1,    0, 1000, 6000], dtype=int32)

In [145]:
arr6=arr5>10
print(arr6.sum())
print(np.sum(arr6))
print(arr5.sum())
print(arr5.any(),arr5.any())
print(arr5.all())
#np.all() check krtahe if all elements are true in np
#np.any()


0
0
0
False False
False


In [151]:
#npz me multiple array aik file me save krsakte he
np.savez('arrays.npz',a=arr5)
arr7=np.load('arrays.npz')
print(arr7['a'])
dct={'a':[1,2,3,4]}
arr8=dct['a']
arr8

[-1 -1 45  6  8  9  1 11]


[1, 2, 3, 4]

In [175]:
#flatten 1d me convert krde ga
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
c=np.concatenate([a,b],axis=0)
c

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [176]:
# vstack and hstack sawal aega
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])